#<< system_password
Password=123
#>> system_password

#<< wizard_tz
NTPServer=tw.pool.ntp.org
TimeZoneList=20
timezone=CST+480
#>> wizard_tz

#<< nat_portmap
Count=1
MIP1=19.60
MName1="Camera1"
MMAC1="a02ef300c2a1"
MAUTH1="0"
MUSER1="admin"
MPWD1="admin"
P1Rtsp=554
P1MRtsp=1031
P1Page=80
P1MPage=1081
P1AN1="live.sdp"
P1AN2="live2.sdp"
P1MDual="1"
PIR1="0"
SNAPSHOT1="0"
ZONE1="0"
Enable=1
#>> nat_portmap

#<< system_zero
dhcps_ip=
#>> system_zero

#<< wan_3gpp
Net3G=1
POINT3G=1
#>> wan_3gpp

#<< system_sms
message_enable="NO"
msg_Select=1
msgnum1=
msgnum2=
msgnun3=
msgnum4=
msgnum5=
msgnum6=""
#>> system_sms

#<< system_zone
chk1=0
sel1=0
txt1=
chk2=0
sel2=0
txt2=
chk3=0
sel3=0
txt3=
chk4=0
sel4=0
txt4=
chk5=0
sel5=0
txt5=
chk6=0
sel6=0
txt6=
chk7=0
sel7=0
txt7=
chk8=0
sel8=0
txt8=
chk9=0
sel9=0
txt9=
chk10=0
sel10=0
txt10=
#>> system_zone

#<< system_mail
MailSvr1="30 15 * * *"
SenderMail1="40 15 * * *"
MailSvr2="10 16 * * *"
SenderMail2="15 16 * * *"
MailSvr3=""
SenderMail3=""
MailSvr4=""
SenderMail4=""
#>> system_mail

#<< system_Alarm
 AlarmTime="00001"
Alarm1="0"
Alarm2="0"
Alarm3="0"
Alarm4="0"
Alarm5="0"
IncomingDelay="1"
OutgoingDelay="1"
#>> system_Alarm

#<< system_log
CustomerID=""
SYSLOG_SVR=""
#>> system_log

#<< temperature_unit
Unit="1"
#>> temperature_unit

#<< cam_rec
Cam1Rec="0"
Cam2Rec="0"
Cam3Rec="0"
Cam4Rec="0"
#>> cam_rec

#<< security_mode
mode=1
#>> security_mode

#<< system_sia
SIA_SVR=""
SIA_PORT="9990"
SIA_ACCT="0"
SIA_PREF="0"
SIA_RECVR="0"
#>> system_sia

#<< gateway_info
FW_VERSION=001.00.079C
WAN_IP=192.168.210.107
LAN_IP=192.168.19.254
DDNS=
SSID=5052040431
WIFI_MAC=A02EF30257E2

#>> gateway_info
  
#<< system_lang
language=tc
#>> system_lang

#<< company
company_name=uisco
#>> company
 
#<< lowbat_siren
enable="1"
#>> lowbat_siren

#<< dev_list_check
enable="0"
#>> dev_list_check

#<< tamper_cacel
enable="0"
#>> tamper_cacel

#<< ieee_addr
hex="0123456789ABCDEF"
#>> ieee_addr

#<< panid
hex="1234"
#>> panid

#<< init_system
value=1
#>> init_system

#<< lighting_group
POWERON=0
#>> lighting_group

